### ISSUE TITLE
Running Nebula Serve on sn-action-button states peer dependency requirement

### ISSUE THREAD

**Issue by goldbergjeffrey** [qlik-oss/nebula.js#634]
## 🐛 Bug report

cross-posting with https://github.com/qlik-oss/sn-action-button/issues/210

when running nebula serve...

```
nebula serve
@nebula.js/supernova should be specified as a peer dependency
```

Is this package even required now when stardust is in place?

### Steps to Reproduce

1. Clone sn-action-button repo
2. npm install
3. nebula serve

whammy

### Expected behavior

it just works

### Actual behavior

lots of tracing messages

### Versions

I thought I was running latest but according to my ide nebula --version returns 0.2.0-alpha.1

### Additional context

(Add any other context, link to demo or screenshots about the issue.)

**Comment by goldbergjeffrey** [comment]
I should add:

```
 ERROR  Failed to compile


Error: 'useElement' is not exported by node_modules/@nebula.js/stardust/index.js
    at error (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:9803:16)
    at handleMissingExport (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:9704:28)
    at Module.traceVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:10142:24)
    at ModuleScope.findVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:8749:39)
    at FunctionScope.findVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at FunctionScope.findVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/usr/local/lib/node_modules/@nebula.js/cli/node_modules/rollup/dist/shared/node-entry.js:4403:40)
(node:36019) UnhandledPromiseRejectionWarning: [object Object]
(node:36019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:36019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by goldbergjeffrey** [comment]
Figured it out. Need to call npm run start in the project dir.
